name: ci
on:
  push:

env:
  HUSKY: 0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          nvm install
          echo "${NVM_BIN}" >> $GITHUB_PATH
        shell: bash --login {0}
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.1
          run_install: true

      - name: Run check
        run: pnpm check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          nvm install
          echo "${NVM_BIN}" >> $GITHUB_PATH
        shell: bash --login {0}
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.2.1
          run_install: true

      - name: Run build
        run: pnpm build
        env:
          BASE_URL: https://shun-shobon.github.io

      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs:
      - check
      - build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: .
