name: ci
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-versions: 14.15.3
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.14.1
      - run: pnpm install

      - name: Run check
        run: pnpm check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-versions: 14.15.3
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.14.1
      - run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist
